### ISSUE TITLE
Other hardware?

### ISSUE THREAD

**Issue by neuhaus** [ctvarlan/esp8266-radiation#1]
Which hardware has to be used with the project to measure the radiation?

**Comment by ctvarlan** [comment]
I'm sorry for the delay on my answer, but I just found your question. 
I will answer you shortly. Thank you for the interest and question.

**Comment by ctvarlan** [comment]
Here [https://thingspeak.com/channels/9892] is a picture of the actual hardware that send the data to Thingspeak channel. There is a Geiger-Muller radiation detector, on the top of the picture, a DC-DC converter, in the middle, and, at the bottom is the ESP8266-01. Some details concerning this project are here [http://ctv.serveblog.net:5555/WP/wordpress/?p=170] but there is no more Arduino but the ESP. I'll do my best to put a schematics online.

**Comment by neuhaus** [comment]
Thanks!
